configure: check if make and gcc exist or not
A newly installed system could not have `make` or `gcc` which is
essential tools to compile.

It should fails with error messages when `make` and `gcc` are not
installed, which could drive users to install them.

Fixed: #1137

Signed-off-by: Sungho Bae <bsh0236@gmail.com>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -165,6 +165,17 @@ MAKEOVERRIDES=
 
 export CC CFLAGS LD LDFLAGS
 
+check_command() {
+	if ! command -v $1 &>/dev/null
+	then
+		echo "'$1' command is not found"
+		exit 1
+	fi
+}
+
+check_command make
+check_command ${CC}
+
 make -siC ${srcdir}/check-deps check-clean
 make -siC ${srcdir}/check-deps check-build
 
